services:
  - type: web
    name: fastapi-meta-trade
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        value: postgresql://meta_user:F38PVqnnMUsHwJ97egdD0W7rYLIbHL5Q@dpg-d1jsf6vdiees73cgfqf0-a.virginia-postgres.render.com/meta_trade
